### ISSUE TITLE
secret tool cannot overwrite values

### ISSUE THREAD

**Issue by kiranjulapalli** [aspnet/UserSecrets#92] opened 2016-08-23 16:27 UTC
Create a new project with work and school account authentication using Microsoft AD.
In the project folder, run 
```
AuthTest\src\AuthTest>dotnet user-secrets list
info: Authentication = {
  "AzureAd": {
    "ClientSecret": "secretmodified"
  }
}
```

Now try to set the value for the ClientSecret
```
AuthTest\src\AuthTest>dotnet user-secrets set Authentication:AzureAd:ClientSecret="AJKHAFU*(@&JKLAS"
info: Successfully saved Authentication:AzureAd:ClientSecret=AJKHAFU*(@&JKLAS =  to the secret store.
```
 
Try to list the value:
```
AuthTest\src\AuthTest>dotnet user-secrets list
info: Authentication = {
  "AzureAd": {
    "ClientSecret": "secretmodified"
  }
}
info: Authentication:AzureAd:ClientSecret=AJKHAFU*(@&JKLAS =
 
```
The tool needs to handle CRUD in a consistent way.
****

**Comment by dougbu** [comment] 2016-08-24 03:21
@muratg @kiranjulapalli this is a duplicate of #79.

Further, the configuration code which reads the secrets treats
``` json
{
  "Authentication": {
    "AzureAd": {
      "ClientSecret": "my secret"
    }
  }
}
```
identically to
``` json
{
  "Authentication:AzureAd:ClientSecret": "my secret"
}
```

Since the later value will be used, the main issue here is that older / ignored values are left in the file.

**Comment by natemcmaster** [comment] 2016-08-24 16:08
Closing as a duplicate of #79, assigning myself to take a look at #79.

**Closed by natemcmaster** 2016-08-24 16:08 UTC
Labels: bug, duplicate
