### ISSUE TITLE
Msbuildify tools

### ISSUE THREAD

**Issue by muratg** [aspnet/UserSecrets#100] opened 2016-09-08 16:44 UTC
### Microsoft.Extensions.SecretManager.Tools
  - Expect to run independently, via the CLI
  - `userSecretId` is in MSBuild or a config file, generated a config file in output or assembly attribute? 
  - No runtime dependency on the project file!

### TODO
  - Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
  - Use desktop msbuild to start our work until the new msbuild is ready for   consumption

### Notes
  - [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
  - [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by natemcmaster** [comment] 2016-09-19 18:57
Closing as duplicate of https://github.com/aspnet/dotnet-watch/issues/161

**Closed by natemcmaster** 2016-09-19 18:57 UTC
