### ISSUE TITLE
`dotnet user-secrets set` does not parse escaped characters correctly

### ISSUE THREAD

**Issue by dougbu** [aspnet/UserSecrets#76] opened 2016-05-12 16:20 UTC
For example the command `dotnet user-secrets set '"""' '"""'` sets a key named `"` to the value `"`. The key and value are escaped correctly in the `secrets.json` file. But what happened to the other quotes?

Similarly
- `dotnet user-secrets set '"quoted"' '"quoted"'` sets a key named `quoted` to the value `quoted` -- no surrounding quotes
- `dotnet user-secrets set 'is "quote"d' 'is "quote"d'` sets a key named `is quoted` to the value `is quoted`
- `dotnet user-secrets set '"' '"'` sets a key named ` ` to the value `null`.

Haven't tried every possible character but suspect this issue is specific to double quotes. For example `dotnet user-secrets set '[23]' '{ "joe": "jones" }'` doesn't mess up the braces or brackets. That sets a key named `[23]` to the value `{ joe: jones }`.

**Comment by dougbu** [comment] 2016-05-12 21:05
Confirmed other characters that `cmd /c` special-cases work fine on Windows. Tried a few escaped newlines. And the PowerShell command
``` powershell
dotnet user-secrets set " &()[]{}^=;!'+,``~ " " &()[]{}^=;!'+,``~ "
```
sets a key named
```
 &()[]{}^=;!'+,`~ 
```
to the value
```
 &()[]{}^=;!'+,`~ 
```

**Comment by dougbu** [comment] 2016-05-12 21:16
Suspect problem affects all tools. `dotnet` may need code where it spawns child processes similar to the DNX [`ScriptExecutor`](https://github.com/aspnet/dnx/blob/199bc294b6c0958336a4a6d5c9eb5b9d31582fa2/src/Microsoft.Dnx.Tooling/Scripts/ScriptExecutor.cs#L60-L71) and the non-Windows (more complicated) code just below that block.

See also the escaped character handling in the [`CommandGrammar`](https://github.com/aspnet/dnx/blob/199bc294b6c0958336a4a6d5c9eb5b9d31582fa2/src/Microsoft.Dnx.Runtime.CommandParsing.Sources/CommandGrammar.cs) class, where DNX parses `scripts` properties in `project.json` files.

**Comment by dougbu** [comment] 2016-05-13 20:19
Looks like the problem is worst on Windows. Finding fewer cases that act strangely on OS X and Linux (Ubuntu 14.04 LTS). For example `dotnet user-secrets set '" a' '" b'` correctly sets the key `" a` to the value `" b`.

On the other hand, `dotnet user-secrets set '" quoted "' '" quoted "'` fails and outputs
```
Specify --help for a list of available options and commands.
critical: Command failed : Unrecognized command or argument '"'
```

**Comment by muratg** [comment] 2016-05-26 06:17
@dougbu would the ideal fix be in individual tools, or the CLI itself?

**Comment by dougbu** [comment] 2016-05-26 15:28
@muratg I only have a suspicion of similar problems in other tools. Suggest testing direct execution of whatever executable or DLL lies behind `dotnet user-secrets`.

**Comment by muratg** [comment] 2016-08-31 16:53
@natemcmaster Assigning for investigation. If other tools suffer similar issues, perhaps the fix would better be at the CLI level.

**Comment by natemcmaster** [comment] 2016-09-01 19:11
@dougbu which shell are you using? I couldn't reproduce this with command prompt.

For more context, dotnet-user-secrets doesn't do anything special to parse quoted values. If there is an issue, it's with how CLI hands off args to internal commands, but so far I haven't found any cases where they do it incorrectly.

**Comment by dougbu** [comment] 2016-09-01 20:35
> which shell are you using?

On Windows, PowerShell though I could use different escapes to pass double quotes when using `cmd`.

On other platforms, `bash`. At least that's what I was using when I found the following case
> `dotnet user-secrets set '" quoted "' '" quoted "'` fails and outputs
```
Specify --help for a list of available options and commands.
critical: Command failed : Unrecognized command or argument '"'
```

----

> it's with how CLI hands off args to internal commands

Wouldn't be surprised if that were the case.

**Comment by natemcmaster** [comment] 2016-09-01 21:14
![image](https://cloud.githubusercontent.com/assets/2696087/18184483/2aff422e-704e-11e6-8ad8-3fb0c63334b5.png)
@dougbu I can't repro it in PowerShell (I'm using preview2 bits). Can you swing by my desk and show me the problem?

**Comment by natemcmaster** [comment] 2016-09-01 22:37
The issue on Bash is in dotnet cli itself: https://github.com/dotnet/cli/issues/4139. Closing as external. We can reopen if we find there are issues in our part of the stack.

**Closed by natemcmaster** 2016-09-01 22:37 UTC
